# YAML configuration for the machine learning project
training:
  epochs: 50
  batch_size: 32
  learning_rate: 0.001
  optimizer: 'adam'

logging:
  level: 'info'
  log_file: 'training.log'

data:
  train_data_path: 'data/train.csv'
  validation_data_path: 'data/validation.csv'
  test_data_path: 'data/test.csv'

model:
  save_path: 'models/model_checkpoint.pth'
  load_path: 'models/model_checkpoint.pth'

environment:
  random_seed: 42
  use_gpu: true